"""
Seed data for Portfolio module.
Provides realistic Angolan BODIVA instruments and brokers.
"""
from decimal import Decimal
from datetime import date

BROKERS = [
    {
        "name": "BFA",
        "full_name": "Banco de Fomento Angola",
        "code": "BFA",
        "is_active": True,
    },
    {
        "name": "BCI",
        "full_name": "Banco Comercial Internacional",
        "code": "BCI",
        "is_active": True,
    },
    {
        "name": "BFA Bolsa",
        "full_name": "BFA - Divisao de Bolsa",
        "code": "BFA_BOLSA",
        "is_active": True,
    },
    {
        "name": "FSDEA",
        "full_name": "Fundo Soberano de Angola",
        "code": "FSDEA",
        "is_active": True,
    },
    {
        "name": "Banco Keve",
        "full_name": "Banco Keve, S.A.",
        "code": "KEVE",
        "is_active": True,
    },
    {
        "name": "BIC",
        "full_name": "Banco Internacional de Credito",
        "code": "BIC",
        "is_active": True,
    },
    {
        "name": "Banco Millennium Atlantico",
        "full_name": "Banco Millennium Atlantico",
        "code": "ATLANTICO",
        "is_active": True,
    },
    {
        "name": "Banco Sol",
        "full_name": "Banco Sol, S.A.",
        "code": "SOL",
        "is_active": True,
    },
    {
        "name": "Banco de Poupanca e Credito",
        "full_name": "Banco de Poupanca e Credito, S.A.",
        "code": "BPC",
        "is_active": True,
    },
]

INSTRUMENTS = [
    # Obrigacoes do Tesouro (OT) - Governo de Angola
    {
        "isin": "AO0812001XXX",
        "ticker": "OT-2026",
        "name": "Obrigacoes do Tesouro Angola 2026",
        "description": "Obrigacoes do Tesouro com vencimento em 2026, juro fixo anual.",
        "instrument_type": "TREASURY_BOND",
        "issuer": "Governo de Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("12.50"),
        "interest_type": "FIXED",
        "issue_date": date(2021, 3, 15),
        "maturity_date": date(2026, 3, 15),
        "frequency_months": 12,
        "current_price": Decimal("102500"),
        "current_yield": Decimal("11.25"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    {
        "isin": "AO0812002XXX",
        "ticker": "OT-2027",
        "name": "Obrigacoes do Tesouro Angola 2027",
        "description": "Obrigacoes do Tesouro com vencimento em 2027, juro fixo anual.",
        "instrument_type": "TREASURY_BOND",
        "issuer": "Governo de Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("14.00"),
        "interest_type": "FIXED",
        "issue_date": date(2022, 6, 20),
        "maturity_date": date(2027, 6, 20),
        "frequency_months": 12,
        "current_price": Decimal("101200"),
        "current_yield": Decimal("12.85"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    {
        "isin": "AO0812003XXX",
        "ticker": "OT-2028",
        "name": "Obrigacoes do Tesouro Angola 2028",
        "description": "Obrigacoes do Tesouro com vencimento em 2028, juro fixo semestral.",
        "instrument_type": "TREASURY_BOND",
        "issuer": "Governo de Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("15.25"),
        "interest_type": "FIXED",
        "issue_date": date(2023, 1, 10),
        "maturity_date": date(2028, 1, 10),
        "frequency_months": 6,
        "current_price": Decimal("99500"),
        "current_yield": Decimal("14.10"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    {
        "isin": "AO0812004XXX",
        "ticker": "OT-2030",
        "name": "Obrigacoes do Tesouro Angola 2030",
        "description": "Obrigacoes do Tesouro longo prazo com vencimento em 2030.",
        "instrument_type": "TREASURY_BOND",
        "issuer": "Governo de Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("16.00"),
        "interest_type": "FIXED",
        "issue_date": date(2024, 5, 8),
        "maturity_date": date(2030, 5, 8),
        "frequency_months": 6,
        "current_price": Decimal("98000"),
        "current_yield": Decimal("15.40"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    {
        "isin": "AO0812005XXX",
        "ticker": "OT-2032",
        "name": "Obrigacoes do Tesouro Angola 2032",
        "description": "Obrigacoes do Tesouro longo prazo com vencimento em 2032.",
        "instrument_type": "TREASURY_BOND",
        "issuer": "Governo de Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("17.00"),
        "interest_type": "FIXED",
        "issue_date": date(2024, 9, 15),
        "maturity_date": date(2032, 9, 15),
        "frequency_months": 12,
        "current_price": Decimal("97500"),
        "current_yield": Decimal("16.50"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    # Bilhetes do Tesouro (BT) - Curto prazo
    {
        "isin": "AO0813001XXX",
        "ticker": "BT-91D",
        "name": "Bilhetes do Tesouro 91 Dias",
        "description": "Bilhetes do Tesouro de curto prazo, 91 dias.",
        "instrument_type": "TREASURY_BILL",
        "issuer": "Governo de Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("18.50"),
        "interest_type": "FIXED",
        "issue_date": date(2026, 2, 1),
        "maturity_date": date(2026, 5, 3),
        "frequency_months": 0,
        "current_price": Decimal("98500"),
        "current_yield": Decimal("18.50"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    {
        "isin": "AO0813002XXX",
        "ticker": "BT-182D",
        "name": "Bilhetes do Tesouro 182 Dias",
        "description": "Bilhetes do Tesouro medio prazo, 182 dias.",
        "instrument_type": "TREASURY_BILL",
        "issuer": "Governo de Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("19.25"),
        "interest_type": "FIXED",
        "issue_date": date(2026, 1, 15),
        "maturity_date": date(2026, 7, 16),
        "frequency_months": 0,
        "current_price": Decimal("97000"),
        "current_yield": Decimal("19.25"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    # Obrigacoes Corporativas
    {
        "isin": "AO4000001XXX",
        "ticker": "BFA-2027",
        "name": "Obrigacoes BFA 2027",
        "description": "Obrigacoes corporativas do Banco de Fomento Angola.",
        "instrument_type": "CORPORATE_BOND",
        "issuer": "Banco de Fomento Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("18.00"),
        "interest_type": "FIXED",
        "issue_date": date(2023, 4, 1),
        "maturity_date": date(2027, 4, 1),
        "frequency_months": 6,
        "current_price": Decimal("100500"),
        "current_yield": Decimal("17.45"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    {
        "isin": "AO4000002XXX",
        "ticker": "UNITEL-2028",
        "name": "Obrigacoes Unitel 2028",
        "description": "Obrigacoes corporativas da Unitel S.A.",
        "instrument_type": "CORPORATE_BOND",
        "issuer": "Unitel S.A.",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("20.00"),
        "interest_type": "FIXED",
        "issue_date": date(2024, 2, 15),
        "maturity_date": date(2028, 2, 15),
        "frequency_months": 12,
        "current_price": Decimal("101000"),
        "current_yield": Decimal("19.35"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    {
        "isin": "AO4000003XXX",
        "ticker": "BIC-2026",
        "name": "Obrigacoes BIC 2026",
        "description": "Obrigacoes corporativas do Banco Internacional de Credito.",
        "instrument_type": "CORPORATE_BOND",
        "issuer": "Banco Internacional de Credito",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("16.50"),
        "interest_type": "FIXED",
        "issue_date": date(2023, 8, 1),
        "maturity_date": date(2026, 8, 1),
        "frequency_months": 6,
        "current_price": Decimal("99500"),
        "current_yield": Decimal("15.80"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    # Certificados de Deposito
    {
        "isin": "AO5000001XXX",
        "ticker": "CD-BFA-6M",
        "name": "Certificado de Deposito BFA 6 Meses",
        "description": "Certificado de deposito a 6 meses do BFA.",
        "instrument_type": "CERTIFICATE",
        "issuer": "Banco de Fomento Angola",
        "face_value": Decimal("50000"),
        "coupon_rate": Decimal("14.50"),
        "interest_type": "FIXED",
        "issue_date": date(2026, 1, 1),
        "maturity_date": date(2026, 7, 1),
        "frequency_months": 0,
        "current_price": Decimal("50000"),
        "current_yield": Decimal("14.50"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    # Additional Treasury Bonds
    {
        "isin": "AO0812006XXX",
        "ticker": "OT-2029",
        "name": "Obrigacoes do Tesouro Angola 2029",
        "description": "Obrigacoes do Tesouro Serie 2029, juro fixo semestral.",
        "instrument_type": "TREASURY_BOND",
        "issuer": "Governo de Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("15.50"),
        "interest_type": "FIXED",
        "issue_date": date(2023, 7, 20),
        "maturity_date": date(2029, 7, 20),
        "frequency_months": 6,
        "current_price": Decimal("99200"),
        "current_yield": Decimal("14.85"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    {
        "isin": "AO0812007XXX",
        "ticker": "OT-2031",
        "name": "Obrigacoes do Tesouro Angola 2031",
        "description": "Obrigacoes do Tesouro Serie 2031, juro fixo anual.",
        "instrument_type": "TREASURY_BOND",
        "issuer": "Governo de Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("16.25"),
        "interest_type": "FIXED",
        "issue_date": date(2024, 1, 15),
        "maturity_date": date(2031, 1, 15),
        "frequency_months": 12,
        "current_price": Decimal("98100"),
        "current_yield": Decimal("15.80"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    {
        "isin": "AO0812008XXX",
        "ticker": "OT-2033",
        "name": "Obrigacoes do Tesouro Angola 2033",
        "description": "Obrigacoes do Tesouro Serie 2033, juro fixo semestral.",
        "instrument_type": "TREASURY_BOND",
        "issuer": "Governo de Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("17.50"),
        "interest_type": "FIXED",
        "issue_date": date(2024, 11, 1),
        "maturity_date": date(2033, 11, 1),
        "frequency_months": 6,
        "current_price": Decimal("97800"),
        "current_yield": Decimal("16.95"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    # Additional Treasury Bills
    {
        "isin": "AO0813003XXX",
        "ticker": "BT-364D",
        "name": "Bilhetes do Tesouro 364 Dias",
        "description": "Bilhetes do Tesouro longo prazo, 364 dias.",
        "instrument_type": "TREASURY_BILL",
        "issuer": "Governo de Angola",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("19.75"),
        "interest_type": "FIXED",
        "issue_date": date(2025, 6, 3),
        "maturity_date": date(2026, 6, 2),
        "frequency_months": 0,
        "current_price": Decimal("94000"),
        "current_yield": Decimal("19.75"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    # Additional Corporate Bonds
    {
        "isin": "AO4000004XXX",
        "ticker": "ATL-2027",
        "name": "Obrigacoes Atlantico 2027",
        "description": "Obrigacoes corporativas do Banco Millennium Atlantico.",
        "instrument_type": "CORPORATE_BOND",
        "issuer": "Banco Millennium Atlantico",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("17.25"),
        "interest_type": "FIXED",
        "issue_date": date(2024, 3, 1),
        "maturity_date": date(2027, 3, 1),
        "frequency_months": 6,
        "current_price": Decimal("99800"),
        "current_yield": Decimal("16.70"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    {
        "isin": "AO4000005XXX",
        "ticker": "ANGOLATEL-2029",
        "name": "Obrigacoes Angolatelecom 2029",
        "description": "Obrigacoes corporativas da Angola Telecom.",
        "instrument_type": "CORPORATE_BOND",
        "issuer": "Angola Telecom",
        "face_value": Decimal("100000"),
        "coupon_rate": Decimal("18.50"),
        "interest_type": "FIXED",
        "issue_date": date(2024, 6, 15),
        "maturity_date": date(2029, 6, 15),
        "frequency_months": 12,
        "current_price": Decimal("100200"),
        "current_yield": Decimal("17.90"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
    # Commercial Paper
    {
        "isin": "AO6000001XXX",
        "ticker": "CP-BFA-180D",
        "name": "Papel Comercial BFA 180 Dias",
        "description": "Papel comercial do BFA, 180 dias.",
        "instrument_type": "COMMERCIAL_PAPER",
        "issuer": "Banco de Fomento Angola",
        "face_value": Decimal("50000"),
        "coupon_rate": Decimal("16.00"),
        "interest_type": "FIXED",
        "issue_date": date(2025, 12, 1),
        "maturity_date": date(2026, 5, 30),
        "frequency_months": 0,
        "current_price": Decimal("49500"),
        "current_yield": Decimal("16.00"),
        "withholding_tax": Decimal("10.00"),
        "is_active": True,
        "currency": "AOA",
    },
]
